spring.application.name=property-management

jwt.secret=TA6UOHZIiZur0WEfZ/SxySFtivREaDOk7kHLPXvF9IAg+o+UKb+XgSB1tKHU8e+8I46d6/OjKZGlwFA+gCMrAw==
jwt.expiration=3600000
jwt.refresh-expiration=604800000
jwt.reset-password-expiration=900000
