spring.application.name=property-management
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/trevix
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=HiiiXknv7SWK69DXGYYLnKUR2g+i/ZxNrvZwr7myun+wF0nPikqiu/GJV2Pn+gxGEae2ow6Pks29/mEvR9vvYA==
jwt.expiration=86400000
jwt.refresh-expiration=604800000
jwt.reset-password-expiration=3600000